baseURL = "https://townsiteuf.org/"
languageCode = "en-us"
title = "TUF"
paginate = 10

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[params]
  description = "A small-scale urban farm in downtown Flagstaff, Arizona that aims to create a resilient community network through permaculture principles, collaborative learning, and social connectivity."
  email = "info@townsiteuf.org"
  whatsappInviteUrl = "https://chat.whatsapp.com/CqvjMoDGmWa9VUf2Lr1aGd"
  instagramUrl = "https://www.instagram.com/townsiteurbanfarm"
  weatherStationUrl = "https://www.wunderground.com/dashboard/pws/KAZFLAGS562"
  r2MediaUrl = "https://media.townsiteuf.org"

[security.funcs]
  getenv = ['^HUGO_', '^CI$', '^CF_PAGES_COMMIT_SHA$']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
